"""Nabla training loop with LoRA for live per-scene fine-tuning.

Training paradigm:
1. Base model pre-trained on production scenes (shipped with Omen)
2. Per-scene LoRA fine-tuning triggered after 3+ renders
3. Training data generated by Dr.Jit (Mitsuba differentiable rendering)
4. Nabla Python API: model.train(), loss.backward(), optimizer.step()
"""

import logging
import os
import time

import numpy as np

try:
    import nabla as nb
    from nabla import nn
    import nabla.nn.functional as F
    NABLA_AVAILABLE = True
except ImportError:
    NABLA_AVAILABLE = False

logger = logging.getLogger("omen.training.trainer")

# Training config from lewm.yaml
DEFAULT_LR = 5e-5
DEFAULT_WEIGHT_DECAY = 1e-3
DEFAULT_GRADIENT_CLIP = 1.0
SIGREG_LAMBDA = 0.09


class OmenTrainer:
    """Nabla PyTorch-style trainer for Omen JEPA model."""

    def __init__(self, model, lr=DEFAULT_LR, weight_decay=DEFAULT_WEIGHT_DECAY):
        if not NABLA_AVAILABLE:
            raise ImportError("Nabla required for training")

        self.model = model
        self.lr = lr
        self.weight_decay = weight_decay
        self.optimizer = nn.optim.AdamW(
            model.parameters(),
            lr=lr,
            weight_decay=weight_decay,
        )
        self.iteration = 0

    def train_step(self, noisy, ground_truth, scene_graph):
        """Run a single training step.

        Args:
            noisy: (batch, H, W, 4) noisy render
            ground_truth: (batch, H, W, 4) clean ground truth
            scene_graph: dict of tensors

        Returns:
            dict with loss values
        """
        self.model.train()

        # Forward pass
        latent = self.model.encode(scene_graph, noisy)
        predicted = self.model.decode(latent, ground_truth.shape[1], ground_truth.shape[2])

        # Compute losses
        pred_loss = F.mse_loss(predicted, ground_truth)
        sigreg_loss = self.model.sigreg(latent)
        total_loss = pred_loss + SIGREG_LAMBDA * sigreg_loss

        # Backward pass
        total_loss.backward()

        # Gradient clipping
        _clip_grad_norm(self.model.parameters(), DEFAULT_GRADIENT_CLIP)

        # Optimizer step
        self.optimizer.step()
        self.optimizer.zero_grad()

        self.iteration += 1

        return {
            "total_loss": float(total_loss.numpy().sum()),
            "pred_loss": float(pred_loss.numpy().sum()),
            "sigreg_loss": float(sigreg_loss.numpy().sum()),
            "iteration": self.iteration,
        }

    def save_checkpoint(self, path):
        """Save model and optimizer state."""
        os.makedirs(os.path.dirname(path), exist_ok=True)

        state = {
            "model": self.model.state_dict(),
            "iteration": self.iteration,
            "lr": self.lr,
        }
        nb.save(state, path)
        logger.info("Checkpoint saved: %s (iter %d)", path, self.iteration)

    def load_checkpoint(self, path):
        """Load model and optimizer state."""
        state = nb.load(path)
        self.model.load_state_dict(state["model"])
        self.iteration = state.get("iteration", 0)
        logger.info("Resumed from iteration %d", self.iteration)

    def init_lora(self, rank=8):
        """Initialize LoRA adapter for parameter-efficient fine-tuning."""
        try:
            from nabla.nn.finetune.lora import init_lora_adapter
            init_lora_adapter(self.model, rank=rank)
            logger.info("LoRA adapter initialized (rank=%d)", rank)
        except ImportError:
            logger.warning("LoRA not available in this Nabla version")


def _clip_grad_norm(parameters, max_norm):
    """Clip gradient norm to prevent explosion."""
    try:
        total_norm = 0.0
        for p in parameters:
            if p.grad is not None:
                total_norm += (p.grad ** 2).sum().numpy().item()
        total_norm = total_norm ** 0.5

        if total_norm > max_norm:
            scale = max_norm / (total_norm + 1e-6)
            for p in parameters:
                if p.grad is not None:
                    p.grad = p.grad * scale
    except Exception:
        pass  # Gradient clipping is best-effort
