"""Nabla training loop with LoRA for live per-scene fine-tuning.

Training paradigm:
1. Base model pre-trained on production scenes (shipped with Omen)
2. Per-scene LoRA fine-tuning triggered after 3+ renders
3. Training data generated by Dr.Jit (Mitsuba differentiable rendering)
4. Nabla Python API: model.train(), loss.backward(), optimizer.step()
"""

import logging
import os
import time

import numpy as np

try:
    import nabla as nb
    from nabla import nn
    import nabla.nn.functional as F
    NABLA_AVAILABLE = True
except ImportError:
    NABLA_AVAILABLE = False

logger = logging.getLogger("omen.training.trainer")

# Training config from lewm.yaml
DEFAULT_LR = 5e-5
DEFAULT_WEIGHT_DECAY = 1e-3
DEFAULT_GRADIENT_CLIP = 1.0
SIGREG_LAMBDA = 0.09


class OmenTrainer:
    """Nabla PyTorch-style trainer for Omen JEPA model."""

    def __init__(self, model, lr=DEFAULT_LR, weight_decay=DEFAULT_WEIGHT_DECAY):
        if not NABLA_AVAILABLE:
            raise ImportError("Nabla required for training")

        self.model = model
        self.lr = lr
        self.weight_decay = weight_decay
        self.optimizer = nn.optim.AdamW(
            model,
            lr=lr,
            weight_decay=weight_decay,
        )
        self.iteration = 0

    def train_step(self, noisy, ground_truth, scene_graph):
        """Run a single JEPA training step — in LATENT space, not pixel space.

        JEPA paradigm: encode both noisy and clean renders into latent space,
        then train the model to predict the clean latent from the noisy latent.
        The decoder is NOT used during training. It's only for inference output.

        Args:
            noisy: (batch, H, W, 4) noisy render
            ground_truth: (batch, H, W, 4) clean ground truth
            scene_graph: dict of tensors

        Returns:
            dict with loss values
        """
        self.model.train()

        # Encode noisy render -> predicted latent
        predicted_latent = self.model.encode(scene_graph, noisy)

        # Encode clean ground truth -> target latent (stop-grad not needed,
        # we want the model to match this representation)
        target_latent = self.model.encode(scene_graph, ground_truth)

        # JEPA loss: latent prediction + SIGReg collapse prevention
        total_loss, pred_loss, sigreg_loss = self.model.compute_loss(
            predicted_latent, target_latent, embeddings=predicted_latent,
            lambda_sigreg=SIGREG_LAMBDA,
        )

        # Backward pass
        total_loss.backward()

        # Gradient clipping
        _clip_grad_norm(self.model.parameters(), DEFAULT_GRADIENT_CLIP)

        # Optimizer step (Nabla returns updated model)
        self.model = self.optimizer.step()
        self.model.zero_grad()

        self.iteration += 1

        return {
            "total_loss": float(total_loss.to_numpy().sum()),
            "pred_loss": float(pred_loss.to_numpy().sum()),
            "sigreg_loss": float(sigreg_loss.to_numpy().sum()),
            "iteration": self.iteration,
        }

    def save_checkpoint(self, path):
        """Save model state dict to disk via numpy .npz serialization."""
        os.makedirs(os.path.dirname(path), exist_ok=True)

        # Convert state_dict tensors to numpy for serialization
        state_dict = self.model.state_dict()
        save_data = {
            "__iteration__": np.array(self.iteration),
            "__lr__": np.array(self.lr),
        }
        for key, tensor in state_dict.items():
            save_data[key] = tensor.to_numpy()

        np.savez_compressed(path, **save_data)
        logger.info("Checkpoint saved: %s (iter %d)", path, self.iteration)

    def load_checkpoint(self, path):
        """Load model state dict from disk."""
        npz_path = path if path.endswith(".npz") else path + ".npz"
        data = np.load(npz_path)
        # Rebuild state dict with Nabla tensors
        state_dict = {}
        for key in data.files:
            if key.startswith("__"):
                continue
            state_dict[key] = nb.Tensor.from_dlpack(data[key])
        self.model.load_state_dict(state_dict)
        self.iteration = int(data.get("__iteration__", 0))
        logger.info("Resumed from iteration %d", self.iteration)

    def init_lora(self, rank=8):
        """Initialize LoRA adapters on all Linear weight parameters.

        Nabla LoRA API: init_lora_adapter(weight, rank) returns {'A', 'B'}.
        Adapters are stored per-parameter for use with lora_linear().
        """
        try:
            from nabla.nn.finetune.lora import init_lora_adapter
            self._lora_adapters = {}
            for name, param in self.model.named_parameters():
                if param.ndim == 2:  # Linear weight matrices
                    self._lora_adapters[name] = init_lora_adapter(param, rank=rank)
            logger.info("LoRA adapters initialized (rank=%d) on %d params",
                        rank, len(self._lora_adapters))
        except ImportError:
            logger.warning("LoRA not available in this Nabla version")


def _clip_grad_norm(parameters, max_norm):
    """Clip gradient norm to prevent explosion."""
    try:
        total_norm = 0.0
        for p in parameters:
            if p.grad is not None:
                total_norm += (p.grad ** 2).sum().to_numpy().item()
        total_norm = total_norm ** 0.5

        if total_norm > max_norm:
            scale = max_norm / (total_norm + 1e-6)
            for p in parameters:
                if p.grad is not None:
                    p.grad = p.grad * scale
    except Exception:
        pass  # Gradient clipping is best-effort
